info:
  app:
    description: This another Star Wars movies repository with some more details
    java:
      version: Java 17
    name: A Star Wars movies repository

spring:
  application:
    name: starwars-movies-repo
  profiles:
    active: dev
  webflux:
    base-path: /api/v1/
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

server:
  port: 8080
  shutdown: graceful

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  packagesToScan: com.jpenacho.starwarsmovierepo
  pathsToMatch: /**
  swagger-ui:
    disable-swagger-default-url: false
    doc-expansion: none
    operations-sorter: alpha
    path: /swagger-ui.html
    tags-sorter: alpha